Beginning of the german translation
robotex140/Hydrocraft pull request #64
Opened 2022-05-11 08:04 UTC by TheSoulrester

Adding and translating of:
+ ContextMenu_DE.txt
+ Farming_DE.txt
+ IG_UI_DE.txt
+ Items_DE.txt
+ Sandbox_DE.txt
+ Tooltip_DE.txt

2022-05-23 16:56 UTC, robotex140 requested changes
please remove the changes you have made to the russian translation. I think you have changed the encoding of the file

2022-05-24 11:18 UTC, TheSoulrester commented
> please remove the changes you have made to the russian translation. I think you have changed the encoding of the file

Sorry for the question: how will i do this?

i wasn't able to discard the change. thats why i made a new pull with the old official ru translation file :D

2022-05-24 17:39 UTC, robotex140 commented
can't figure out why the change can't be reverted. Not sure what the difference here is, so just will let it through as see what happens. It ultimately does encode into utf-8 from what I can tell. I thought it would be safer to remove that change but can't figure it out.

2022-05-24 17:39 UTC, robotex140 approved these changes

2022-05-24 17:39 UTC, merged